name: CI
on:
  push:
    branches: [main,develop]
  workflow_dispatch:
jobs:
  release_gs:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          ./build.sh
