name: CI
on:
  push:
    branches: [main,develop]
  workflow_dispatch:
jobs:
  release_gs:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          ./build.sh
          echo 'Release version' >> body.md
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "body.md"
          artifacts: "ghostscript.zip"
          tag: 10.02.0
