name: CI
on:
  push:
    branches: [main,develop]
  workflow_dispatch:
env:
jobs:
  release_gs:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          # ./build.sh
          cat 'Release version' >> body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: body.md